### ISSUE TITLE
Bundler incompatibility when using Vagrant 

### ISSUE THREAD

**Issue by christinedraper** [chef-cookbooks/delivery-cluster#181]
When I run `rake setup:cluster` it fails converging the chef server as below. It seems to be because chef-provisioning is running vagrant in an env that only includes the chefdk embedded gems, and vagrant requires 1.10.5 whereas chefDK has 1.10.6. Any suggested workaround? I was so looking forward to trying out delivery!

```   ================================================================================
    Error executing action `converge` on resource 'machine[chef-server-test]'
    ================================================================================
    
    RuntimeError
    ------------
    vagrant up chef-server-test --provider virtualbox failed!
    STDOUT:
    STDERR:Vagrant experienced a version conflict with some installed plugins!
    This usually happens if you recently upgraded Vagrant. As part of the
    upgrade process, some existing plugins are no longer compatible with
    this version of Vagrant. The recommended way to fix this is to remove
    your existing plugins and reinstall them one-by-one. To remove all
    plugins:
    
        rm -r ~/.vagrant.d/plugins.json ~/.vagrant.d/gems
    
    Note if you have an alternate VAGRANT_HOME environmental variable
    set, the folders above will be in that directory rather than your
    user's home directory.
    
    The error message is shown below:
    
    Bundler could not find compatible versions for gem "bundler":
      In Gemfile:
        vagrant (= 1.7.4) ruby depends on
          bundler (<= 1.10.5, >= 1.5.2) ruby
    
      Current Bundler version:
        bundler (1.10.6)
    This Gemfile requires a different version of Bundler.
    Perhaps you need to update Bundler by running `gem install bundler`?
    Could not find gem 'bundler (<= 1.10.5, >= 1.5.2) ruby', which is required by gem 'vagrant (= 1.7.4) ruby', in any of the sources.

    Compiled Resource:
    ------------------
    # Declared in /home/christine/git/delivery/delivery-cluster/.chef/local-mode-cache/cache/cookbooks/delivery-cluster/recipes/setup_chef_server.rb:31:in `from_file'
    
    machine("chef-server-test") do
      action [:converge]
      retries 0
      retry_delay 2
      default_guard_interpreter :default
      chef_server {:chef_server_url=>"chefzero://localhost:8890", :options=>{:client_name=>"delivery", :signing_key_filename=>nil, :api_version=>"0"}}
      driver "vagrant"
      machine_options #<Cheffish::MergedConfig:0x00000004834cb8 @configs=[{:vagrant_config=>"  config.vm.provider :virtualbox do |v|\n    v.customize [\"modifyvm\", :id,'--memory', 2048]\n    v.customize [\"modifyvm\", :id, '--cpus', 2]\n  end\n"}, #<Cheffish::MergedConfig:0x00000004834d58 @configs=[{:vagrant_options=>{"vm.network"=>":private_network, {:ip => '33.33.33.10'}"}}, #<Cheffish::MergedConfig:0x00000004834e20 @configs=[{:vagrant_options=>{"vm.hostname"=>"chef.example.com"}}, {:convergence_options=>{:bootstrap_proxy=>nil, :chef_config=>nil, :chef_version=>nil}, :vagrant_options=>{"vm.box"=>"opscode-ubuntu-14.04", "vm.box_url"=>"https://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_ubuntu-14.04_chef-provisionerless.box", "vm.hostname"=>nil}, :vagrant_config=>nil, :transport_options=>{:options=>{:prefix=>"sudo "}}, :use_private_ip_for_ssh=>true}], @merge_arrays={}>], @merge_arrays={}>], @merge_arrays={}>
      declared_type :machine
      cookbook_name "delivery-cluster"
      recipe_name "setup_chef_server"
    end
    

Running handlers:
[2015-12-10T17:09:12-06:00] ERROR: Running exception handlers
Running handlers complete
[2015-12-10T17:09:12-06:00] ERROR: Exception handlers complete
Chef Client failed. 1 resources updated in 11.343633558 seconds
```

Stacktrace:

```
Generated at 2015-12-10 17:09:12 -0600
RuntimeError: machine[chef-server-test] (delivery-cluster::setup_chef_server line 31) had an error: RuntimeError: vagrant up chef-server-test --provider virtualbox failed!
STDOUT:
STDERR:Vagrant experienced a version conflict with some installed plugins!
<snip - message as in run output>

/home/christine/git/delivery/delivery-cluster/vendor/bundle/ruby/2.1.0/bundler/gems/chef-provisioning-vagrant-05bcff260bde/lib/chef/provisioning/vagrant_driver/driver.rb:255:in `block in start_machine'
/home/christine/git/delivery/delivery-cluster/vendor/bundle/ruby/2.1.0/gems/chef-12.4.3/lib/chef/mixin/why_run.rb:52:in `call'
/home/christine/git/delivery/delivery-cluster/vendor/bundle/ruby/2.1.0/gems/chef-12.4.3/lib/chef/mixin/why_run.rb:52:in `add_action'
/home/christine/git/delivery/delivery-cluster/vendor/bundle/ruby/2.1.0/gems/chef-12.4.3/lib/chef/provider.rb:175:in `converge_by'
/home/christine/git/delivery/delivery-cluster/vendor/bundle/ruby/2.1.0/bundler/gems/chef-provisioning-0acb58a661eb/lib/chef/provisioning/chef_provider_action_handler.rb:54:in `perform_action'
/home/christine/git/delivery/delivery-cluster/vendor/bundle/ruby/2.1.0/bundler/gems/chef-provisioning-vagrant-05bcff260bde/lib/chef/provisioning/vagrant_driver/driver.rb:251:in `start_machine'
/home/christine/git/delivery/delivery-cluster/vendor/bundle/ruby/2.1.0/bundler/gems/chef-provisioning-vagrant-05bcff260bde/lib/chef/provisioning/vagrant_driver/driver.rb:73:in `ready_machine'
/home/christine/git/delivery/delivery-cluster/vendor/bundle/ruby/2.1.0/bundler/gems/chef-provisioning-0acb58a661eb/lib/chef/provider/machine.rb:39:in `block in <class:Machine>'
/home/christine/git/delivery/delivery-cluster/vendor/bundle/ruby/2.1.0/gems/chef-12.4.3/lib/chef/provider/lwrp_base.rb:61:in `instance_eval'
/home/christine/git/delivery/delivery-cluster/vendor/bundle/ruby/2.1.0/gems/chef-12.4.3/lib/chef/provider/lwrp_base.rb:61:in `recipe_eval_with_update_check'
/home/christine/git/delivery/delivery-cluster/vendor/bundle/ruby/2.1.0/gems/chef-12.4.3/lib/chef/provider/lwrp_base.rb:46:in `block in action'
/home/christine/git/delivery/delivery-cluster/vendor/bundle/ruby/2.1.0/bundler/gems/chef-provisioning-0acb58a661eb/lib/chef/provider/machine.rb:56:in `block in <class:Machine>'
/home/christine/git/delivery/delivery-cluster/vendor/bundle/ruby/2.1.0/gems/chef-12.4.3/lib/chef/provider/lwrp_base.rb:61:in `instance_eval'
/home/christine/git/delivery/delivery-cluster/vendor/bundle/ruby/2.1.0/gems/chef-12.4.3/lib/chef/provider/lwrp_base.rb:61:in `recipe_eval_with_update_check'
/home/christine/git/delivery/delivery-cluster/vendor/bundle/ruby/2.1.0/gems/chef-12.4.3/lib/chef/provider/lwrp_base.rb:46:in `block in action'
<snip>
```
Versions:

```
> chef --version
Chef Development Kit Version: 0.10.0
chef-client version: 12.5.1
berks version: 4.0.1
kitchen version: 1.4.2
> vagrant --version
Vagrant 1.7.4
```

**Comment by christinedraper** [comment]
I think I have worked around the problem by doing:
```
bundle _1.10.5_ install  --path vendor/bundle
bundle _1.10.5_ exec rake setup:cluster
```
I did get an error message, apparently from berks vendor, but it does not seem to be causing an issue yet (install still in progress as I write).

```
Vendoring yum (3.8.2) to cookbooks/yum
Vendoring yum-chef (0.2.1) to cookbooks/yum-chef
Vendoring yum-epel (0.6.4) to cookbooks/yum-epel
/opt/chefdk/embedded/lib/ruby/2.1.0/fileutils.rb:1402:in `initialize': Permission denied @ rb_sysopen - /home/christine/git/delivery/delivery-cluster/cookbooks/delivery-cluster/cookbooks/delivery-cluster/cookbooks/delivery-cluster/cookbooks/delivery-cluster/vendor/bundle/ruby/2.1.0/cache/bundler/git/chef-provisioning-aws-183ef639edee31c570d7034fb4756b1bf3422e64/objects/pack/pack-4734b7cf5d3a5f909ddaaa0547f925115785f63a.idx (Errno::EACCES)
	from /opt/chefdk/embedded/lib/ruby/2.1.0/fileutils.rb:1402:in `open'
	from /opt/chefdk/embedded/lib/ruby/2.1.0/fileutils.rb:1402:in `block in copy_file'
	from /opt/chefdk/embedded/lib/ruby/2.1.0/fileutils.rb:1401:in `open'
	from /opt/chefdk/embedded/lib/ruby/2.1.0/fileutils.rb:1401:in `copy_file'
	from /opt/chefdk/embedded/lib/ruby/2.1.0/fileutils.rb:483:in `copy_file'
	from /opt/chefdk/embedded/lib/ruby/2.1.0/fileutils.rb:400:in `block in cp'
	from /opt/chefdk/embedded/lib/ruby/2.1.0/fileutils.rb:1579:in `block in fu_each_src_dest'
	from /opt/chefdk/embedded/lib/ruby/2.1.0/fileutils.rb:1595:in `fu_each_src_dest0'
	from /opt/chefdk/embedded/lib/ruby/2.1.0/fileutils.rb:1577:in `fu_each_src_dest'
	from /opt/chefdk/embedded/lib/ruby/2.1.0/fileutils.rb:399:in `cp'
	from /home/christine/git/delivery/delivery-cluster/vendor/bundle/ruby/2.1.0/gems/berkshelf-3.2.4/lib/berkshelf/file_syncer.rb:89:in `block in sync'
	from /home/christine/git/delivery/delivery-cluster/vendor/bundle/ruby/2.1.0/gems/berkshelf-3.2.4/lib/berkshelf/file_syncer.rb:71:in `each'
	from /home/christine/git/delivery/delivery-cluster/vendor/bundle/ruby/2.1.0/gems/berkshelf-3.2.4/lib/berkshelf/file_syncer.rb:71:in `sync'
	from /home/christine/git/delivery/delivery-cluster/vendor/bundle/ruby/2.1.0/gems/berkshelf-3.2.4/lib/berkshelf/berksfile.rb:624:in `block in vendor'
	from /opt/chefdk/embedded/lib/ruby/2.1.0/tmpdir.rb:88:in `mktmpdir'
	from /home/christine/git/delivery/delivery-cluster/vendor/bundle/ruby/2.1.0/gems/berkshelf-3.2.4/lib/berkshelf/berksfile.rb:581:in `vendor'
	from /home/christine/git/delivery/delivery-cluster/vendor/bundle/ruby/2.1.0/gems/berkshelf-3.2.4/lib/berkshelf/cli.rb:387:in `vendor'
	from /home/christine/git/delivery/delivery-cluster/vendor/bundle/ruby/2.1.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
	from /home/christine/git/delivery/delivery-cluster/vendor/bundle/ruby/2.1.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
	from /home/christine/git/delivery/delivery-cluster/vendor/bundle/ruby/2.1.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
	from /home/christine/git/delivery/delivery-cluster/vendor/bundle/ruby/2.1.0/gems/berkshelf-3.2.4/lib/berkshelf/cli.rb:52:in `dispatch'
	from /home/christine/git/delivery/delivery-cluster/vendor/bundle/ruby/2.1.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
	from /home/christine/git/delivery/delivery-cluster/vendor/bundle/ruby/2.1.0/gems/berkshelf-3.2.4/lib/berkshelf/cli.rb:27:in `execute!'
	from /home/christine/git/delivery/delivery-cluster/vendor/bundle/ruby/2.1.0/gems/berkshelf-3.2.4/bin/berks:5:in `<top (required)>'
	from /home/christine/git/delivery/delivery-cluster/vendor/bundle/ruby/2.1.0/bin/berks:23:in `load'
	from /home/christine/git/delivery/delivery-cluster/vendor/bundle/ruby/2.1.0/bin/berks:23:in `<main>'

Current chef environment => environments/test.json


Setup the Chef Delivery cluster
```

```

**Comment by afiune** [comment]
@christinedraper Thank you so much for reporting this issue. We have seen different errors regarding `bundler` and the way we encapsulate the gems in `chefdk`. We are currently working on a change that will remove the dependency to bundler. Glad to hear you have been unblocked. Stay tuned and let us know if you have any other problem.

**Comment by afiune** [comment]
@christinedraper could you try with the latest code from master?

**Comment by christinedraper** [comment]
It works, thanks!
