### ISSUE TITLE
Error running rake setup:cluster in Vagrant action 'run'

### ISSUE THREAD

**Issue by cjohannsen81** [chef-cookbooks/delivery-cluster#205]
Hi,

just tried to use delivery-cluster with vagrant and it fails with:

```
                       Recipe: chef-server-12::default
                         * template[/etc/opscode/chef-server.rb] action create
                           - update content in file /etc/opscode/chef-server.rb from e3b0c4 to 1f4d38
                           --- /etc/opscode/chef-server.rb	2016-03-29 08:56:12.434327678 +0000
                           +++ /etc/opscode/.chef-chef-server.rb20160329-7187-xovtjv	2016-03-29 08:56:13.192706675 +0000
                           @@ -1 +1,6 @@
                           +topology 'standalone'
                           +api_fqdn '10.0.2.15'
                           +nginx['server_name'] = '10.0.2.15'
                           +
                           +
                           - change mode from '0640' to '0644'
                           - restore selinux security context
                         * chef_ingredient[chef-server] action reconfigure
                           * ingredient_config[chef-server] action render (skipped due to not_if)
                           * execute[chef-server-core-reconfigure] action run



                             
                             ================================================================================
                             Error executing action `run` on resource 'execute[chef-server-core-reconfigure]'
                             ================================================================================
                             
                             Mixlib::ShellOut::ShellCommandFailed
                             ------------------------------------
                             Expected process to exit with [0], but received '1'
                             ---- Begin output of chef-server-ctl reconfigure ----
                             STDOUT: [2016-03-29T08:56:16+00:00] INFO: Started chef-zero at chefzero://localhost:8889 with repository at /opt/opscode/embedded
                               One version per cookbook
                             
                             [2016-03-29T08:56:16+00:00] INFO: *** Chef 12.7.0 ***
                             [2016-03-29T08:56:16+00:00] INFO: Chef-client pid: 7881
                             [2016-03-29T08:56:17+00:00] INFO: HTTP Request Returned 404 Not Found: Object not found: chefzero://localhost:8889/nodes/chef.example.com
                             [2016-03-29T08:56:17+00:00] INFO: Setting the run_list to ["recipe[private-chef::default]"] from CLI options
                             [2016-03-29T08:56:17+00:00] INFO: Run List is [recipe[private-chef::default]]
                             [2016-03-29T08:56:17+00:00] INFO: Run List expands to [private-chef::default]
                             [2016-03-29T08:56:17+00:00] INFO: Starting Chef Run for chef.example.com
                             [2016-03-29T08:56:17+00:00] INFO: Running start handlers

```

Here is the config:

```
{
  "name": "test",
  "description": "Delivery Cluster Environment",
  "json_class": "Chef::Environment",
  "chef_type": "environment",
  "override_attributes": {
    "delivery-cluster": {
      "id": "test",
      "driver": "vagrant",
      "vagrant": {
        "ssh_username": "vagrant",
        "vm_box": "opscode-centos-6.6",
        "image_url": "https://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_centos-6.6_chef-provisionerless.box",
        "key_file": "/Users/cjo/.vagrant.d/insecure_private_key"
      },
      "chef-server": {
        "organization": "test",
        "existing": false,
        "vm_hostname": "chef.example.com",
        "network": ":private_network, {:ip => '33.33.33.10'}",
        "vm_memory": "2048",
        "vm_cpus": "2"
      },
      "delivery": {
        "version": "latest",
        "enterprise": "test",
        "license_file": "/Users/cjo/delivery.license",
        "vm_hostname": "delivery.example.com",
        "network": ":private_network, {:ip => '33.33.33.11'}",
        "vm_memory": "2048",
        "vm_cpus": "2"
      },
      "builders": {
        "count": "1",
        "1": {
          "network": ":private_network, {:ip => '33.33.33.14'}",
          "vm_memory": "2048",
          "vm_cpus": "2"
        }
      }
    }
  }
}
```

**Comment by afiune** [comment]
Hi @cjohannsen81 and thank you for the feedback! I would like to know if that is all the logs you have since I think there are more from the `reconfigure` process. The configuration looks good and this should work just fine. If you are still interested in spinning this up please try with the latest version of delivery-cluster and let us know if this is still an issue.

**Comment by sclark007** [comment]
I can confirm this is still a issue. looks like the chef-server ip is not getting set to the IP found in the environment. still digging to figure out where the issue is. 



sclark@steve-pro [~/development/tsa-dev/tsa-chef/cookbooks/delivery-cluster] (master)$ rake setup:cluster

Verifying ChefDK version

Running ChefDK version 0.15.16

Configuring the provisioner node

[2016-08-03T20:11:59-04:00] WARN: chef_gem[chef-provisioning-ssh] chef_gem compile_time installation is deprecated at recipes/provisioner.rb:25:in `block in run_chef_recipe'
[2016-08-03T20:11:59-04:00] WARN: chef_gem[chef-provisioning-ssh] Please set `compile_time false` on the resource to use the new behavior. at recipes/provisioner.rb:25:in `block in run_chef_recipe'
[2016-08-03T20:11:59-04:00] WARN: chef_gem[chef-provisioning-ssh] or set `compile_time true` on the resource if compile_time behavior is required. at recipes/provisioner.rb:25:in `block in run_chef_recipe'
Recipe: (chef-apply cookbook)::(chef-apply recipe)
  * chef_gem[chef-provisioning-ssh] action install (up to date)
[2016-08-03T20:11:59-04:00] WARN: chef_gem[chef-provisioning-vagrant] chef_gem compile_time installation is deprecated at recipes/provisioner.rb:25:in `block in run_chef_recipe'
[2016-08-03T20:11:59-04:00] WARN: chef_gem[chef-provisioning-vagrant] Please set `compile_time false` on the resource to use the new behavior. at recipes/provisioner.rb:25:in `block in run_chef_recipe'
[2016-08-03T20:11:59-04:00] WARN: chef_gem[chef-provisioning-vagrant] or set `compile_time true` on the resource if compile_time behavior is required. at recipes/provisioner.rb:25:in `block in run_chef_recipe'
  * chef_gem[chef-provisioning-vagrant] action install (up to date)
[2016-08-03T20:11:59-04:00] WARN: chef_gem[chef-provisioning-aws] chef_gem compile_time installation is deprecated at recipes/provisioner.rb:25:in `block in run_chef_recipe'
[2016-08-03T20:11:59-04:00] WARN: chef_gem[chef-provisioning-aws] Please set `compile_time false` on the resource to use the new behavior. at recipes/provisioner.rb:25:in `block in run_chef_recipe'
[2016-08-03T20:11:59-04:00] WARN: chef_gem[chef-provisioning-aws] or set `compile_time true` on the resource if compile_time behavior is required. at recipes/provisioner.rb:25:in `block in run_chef_recipe'
  * chef_gem[chef-provisioning-aws] action install (up to date)
[2016-08-03T20:11:59-04:00] WARN: chef_gem[knife-push] chef_gem compile_time installation is deprecated at recipes/provisioner.rb:28:in `run_chef_recipe'
[2016-08-03T20:11:59-04:00] WARN: chef_gem[knife-push] Please set `compile_time false` on the resource to use the new behavior. at recipes/provisioner.rb:28:in `run_chef_recipe'
[2016-08-03T20:11:59-04:00] WARN: chef_gem[knife-push] or set `compile_time true` on the resource if compile_time behavior is required. at recipes/provisioner.rb:28:in `run_chef_recipe'
  * chef_gem[knife-push] action install (up to date)
  * chef_gem[chef-provisioning-ssh] action install (up to date)
  * chef_gem[chef-provisioning-vagrant] action install (up to date)
  * chef_gem[chef-provisioning-aws] action install (up to date)
  * chef_gem[knife-push] action install (up to date)

Download and vendor the necessary cookbooks locally

Resolving cookbook dependencies...
Fetching 'chef-server-12' from source at vendor/chef-server-12
Fetching 'chef-splunk' from https://github.com/chef-cookbooks/chef-splunk.git (at master)
Fetching 'delivery-base' from https://github.com/chef-cookbooks/delivery-base.git (at master)
Fetching 'delivery-cluster' from source at .
Fetching 'delivery_build' from https://github.com/chef-cookbooks/delivery_build.git (at master)
Fetching 'runit' from https://github.com/afiune/runit.git (at afiune/make-it-work-in-oel)
Fetching cookbook index from https://supermarket.chef.io...
Using apt (4.0.1)
Using chef-ingredient (0.19.0)
Using build-essential (6.0.3)
Using chef-splunk (1.6.0) from https://github.com/chef-cookbooks/chef-splunk.git (at master)
Using chef-vault (1.3.3)
Using chef_handler (1.4.0)
Using chef-server-12 (0.1.17) from source at vendor/chef-server-12
Using chef-sugar (3.4.0)
Using compat_resource (12.10.7)
Using delivery-base (0.2.2) from https://github.com/chef-cookbooks/delivery-base.git (at master)
Using delivery-cluster (0.6.15) from source at .
Using delivery_build (0.4.28) from https://github.com/chef-cookbooks/delivery_build.git (at master)
Using dmg (2.4.0)
Using git (4.6.0)
Using hostsfile (2.4.5)
Using mingw (1.2.4)
Using packagecloud (0.2.4)
Using push-jobs (3.2.0)
Using runit (1.7.7) from https://github.com/afiune/runit.git (at afiune/make-it-work-in-oel)
Using seven_zip (2.0.1)
Using windows (1.44.1)
Using yum (3.11.0)
Using yum-epel (0.7.0)
Vendoring apt (4.0.1) to cookbooks/apt
Vendoring build-essential (6.0.3) to cookbooks/build-essential
Vendoring chef-ingredient (0.19.0) to cookbooks/chef-ingredient
Vendoring chef-server-12 (0.1.17) to cookbooks/chef-server-12
Vendoring chef-splunk (1.6.0) to cookbooks/chef-splunk
Vendoring chef-sugar (3.4.0) to cookbooks/chef-sugar
Vendoring chef-vault (1.3.3) to cookbooks/chef-vault
Vendoring chef_handler (1.4.0) to cookbooks/chef_handler
Vendoring compat_resource (12.10.7) to cookbooks/compat_resource
Vendoring delivery-base (0.2.2) to cookbooks/delivery-base
Vendoring delivery-cluster (0.6.15) to cookbooks/delivery-cluster
Vendoring delivery_build (0.4.28) to cookbooks/delivery_build
Vendoring dmg (2.4.0) to cookbooks/dmg
Vendoring git (4.6.0) to cookbooks/git
Vendoring hostsfile (2.4.5) to cookbooks/hostsfile
Vendoring mingw (1.2.4) to cookbooks/mingw
Vendoring packagecloud (0.2.4) to cookbooks/packagecloud
Vendoring push-jobs (3.2.0) to cookbooks/push-jobs
Vendoring runit (1.7.7) to cookbooks/runit
Vendoring seven_zip (2.0.1) to cookbooks/seven_zip
Vendoring windows (1.44.1) to cookbooks/windows
Vendoring yum (3.11.0) to cookbooks/yum
Vendoring yum-epel (0.7.0) to cookbooks/yum-epel

Current chef environment => environments/test.json


Setup the Chef Delivery cluster

Starting Chef Client, version 12.11.18
[2016-08-03T20:12:13-04:00] WARN: Run List override has been provided.
[2016-08-03T20:12:13-04:00] WARN: Original Run List: []
[2016-08-03T20:12:13-04:00] WARN: Overridden Run List: [recipe[delivery-cluster::setup]]
resolving cookbooks for run list: ["delivery-cluster::setup"]
Synchronizing Cookbooks:
  - delivery-cluster (0.6.15)
  - chef-server-12 (0.1.17)
  - chef-ingredient (0.19.0)
  - git (4.6.0)
  - apt (4.0.1)
  - yum (3.11.0)
  - delivery_build (0.4.28)
  - chef-splunk (1.6.0)
  - hostsfile (2.4.5)
  - build-essential (6.0.3)
  - dmg (2.4.0)
  - windows (1.44.1)
  - yum-epel (0.7.0)
  - chef-sugar (3.4.0)
  - compat_resource (12.10.7)
  - delivery-base (0.2.2)
  - chef-vault (1.3.3)
  - seven_zip (2.0.1)
  - mingw (1.2.4)
  - chef_handler (1.4.0)
  - push-jobs (3.2.0)
  - runit (1.7.7)
  - packagecloud (0.2.4)
Installing Cookbook Gems:
Compiling Cookbooks...
[2016-08-03T20:12:18-04:00] WARN: Chef::Provider::AptRepository already exists!  Cannot create deprecation class for LWRP provider apt_repository from cookbook apt
[2016-08-03T20:12:18-04:00] WARN: AptRepository already exists!  Deprecation class overwrites Custom resource apt_repository from cookbook apt
Converging 33 resources
Recipe: delivery-cluster::_settings
  * link[/Users/sclark/development/tsa-dev/tsa-chef/cookbooks/delivery-cluster/.chef/../.chef/delivery-cluster-data] action create
    - create symlink at /Users/sclark/development/tsa-dev/tsa-chef/cookbooks/delivery-cluster/.chef/../.chef/delivery-cluster-data to /Users/sclark/development/tsa-dev/tsa-chef/cookbooks/delivery-cluster/.chef/../.chef/delivery-cluster-data-test
Recipe: delivery-cluster::setup_chef_server
  * machine[chef-server-test] action converge[2016-08-03T20:12:18-04:00] WARN: Class Chef::Provider::VagrantCluster does not declare 'provides :vagrant_cluster'.
[2016-08-03T20:12:18-04:00] WARN: This will no longer work in Chef 13: you must use 'provides' to use the resource's DSL.

    - create new directory /Users/sclark/development/tsa-dev/tsa-chef/cookbooks/delivery-cluster/.chef/vms
    - create new file /Users/sclark/development/tsa-dev/tsa-chef/cookbooks/delivery-cluster/.chef/vms/Vagrantfile
    - update content in file /Users/sclark/development/tsa-dev/tsa-chef/cookbooks/delivery-cluster/.chef/vms/Vagrantfile from none to fe928d
    - --- /Users/sclark/development/tsa-dev/tsa-chef/cookbooks/delivery-cluster/.chef/vms/Vagrantfile	2016-08-03 20:12:18.000000000 -0400
    - +++ /Users/sclark/development/tsa-dev/tsa-chef/cookbooks/delivery-cluster/.chef/vms/.chef-Vagrantfile20160803-7876-d9hxyn	2016-08-03 20:12:18.000000000 -0400
    - @@ -1 +1,4 @@
    - +Dir.glob('/Users/sclark/development/tsa-dev/tsa-chef/cookbooks/delivery-cluster/.chef/vms/*.vm') do |vm_file|
    - +  eval(IO.read(vm_file), nil, vm_file)
    - +end
    - create new file /Users/sclark/development/tsa-dev/tsa-chef/cookbooks/delivery-cluster/.chef/vms/chef-server-test.vm
    - update content in file /Users/sclark/development/tsa-dev/tsa-chef/cookbooks/delivery-cluster/.chef/vms/chef-server-test.vm from none to c00243
    - --- /Users/sclark/development/tsa-dev/tsa-chef/cookbooks/delivery-cluster/.chef/vms/chef-server-test.vm	2016-08-03 20:12:18.000000000 -0400
    - +++ /Users/sclark/development/tsa-dev/tsa-chef/cookbooks/delivery-cluster/.chef/vms/.chef-chef-server-test.vm20160803-7876-kkp4k4	2016-08-03 20:12:18.000000000 -0400
    - @@ -1 +1,13 @@
    - +Vagrant.configure('2') do |outer_config|
    - +  outer_config.vm.define "chef-server-test" do |config|
    - +    config.vm.network(:private_network, {:ip => '33.33.33.10'})
    - +    config.vm.hostname = "chef.example.com"
    - +    config.vm.box = "opscode-centos-6.6"
    - +    config.vm.box_url = "https://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_centos-6.6_chef-provisionerless.box"
    - +  config.vm.provider :virtualbox do |v|
    - +    v.customize ["modifyvm", :id,'--memory', 2048]
    - +    v.customize ["modifyvm", :id, '--cpus', 2]
    - +  end
    - +  end
    - +end
    - create node chef-server-test at chefzero://localhost:8890
    -   add normal.tags = nil
    -   add normal.chef_provisioning = {"reference"=>{"driver_url"=>"vagrant:/Users/sclark/development/tsa-dev/tsa-chef/cookbooks/delivery-cluster/.chef/vms", "driver_version"=>"0.11.0", "vm_name"=>"chef-server-test", "vm_file_path"=>"/Users/sclark/development/tsa-dev/tsa-chef/cookbooks/delivery-cluster/.chef/vms/chef-server-test.vm", "allocated_at"=>"2016-08-04 00:12:18 UTC", "host_node"=>"chefzero://localhost:8890/nodes/", "needs_reload"=>true}}
    - run vagrant up chef-server-test --provider virtualbox (status was 'not created')
    - update node chef-server-test at chefzero://localhost:8890
    -   update normal.chef_provisioning.reference.needs_reload from true to false
    -   add normal.chef_provisioning.reference.forwarded_ports = {}[2016-08-03T20:12:59-04:00] ERROR: Unable to download /etc/chef/client.pem to /tmp/client.pem.2919536416 on vagrant@127.0.0.1 -- Error: command 'cp /etc/chef/client.pem /tmp/client.pem.2919536416' exited with code 1.

[2016-08-03T20:12:59-04:00] WARN: Unable to clean up /tmp/client.pem.2919536416 on vagrant@127.0.0.1 -- Error: command 'rm /tmp/client.pem.2919536416' exited with code 1.


    - generate private key (2048 bits)
    - create directory /etc/chef on chef-server-test
    - write file /etc/chef/client.pem on chef-server-test
    - create client chef-server-test at clients
    -   add public_key = "-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEArhB9oJuxzR6qHWRujndS\nwZ6sVTB0SHOlrnEGuh9ysp9vdsozeQtR9JeyKePrk38poctNOl3duH/AxOvrJEqP\nZ1EjRuOoHKgR+j2I/q2Sdp0XrVVGJtBA47xqWpfKEgp8ydD2jZS2NrR0Oy/fQFiI\n0XDzMz6pXxmdhD0cl81rwKw1Ghuz7mjROikyuEPjpXNjOvx9TQdQTCQEhBV0UFuE\nL5m6cMVNfhvUgLyqKm2IY0q+HRBV+HLrELUhnKOy7p6L85wPZTZQx/5Q85GhErbx\ncATFQiVfxr1qOjHR+2aLhG+RdvnxpGF4c9RtDtvh7kIeM8r3Fg7w+AeB+WiXHpC9\nGwIDAQAB\n-----END PUBLIC KEY-----\n"
    - write file /etc/chef/client.rb on chef-server-test
    - write file /tmp/detect.sh on chef-server-test
    - upload file /Users/sclark/.chef/package_cache/chef-12.12.15-1.el6.x86_64.rpm to /tmp/chef-12.12.15-1.el6.x86_64.rpm on chef-server-test
    - run 'rpm -Uvh --oldpackage --replacepkgs "/tmp/chef-12.12.15-1.el6.x86_64.rpm"' on chef-server-test
    [chef-server-test] Starting Chef Client, version 12.12.15
                       resolving cookbooks for run list: []
                       Synchronizing Cookbooks:
                       Installing Cookbook Gems:
                       Compiling Cookbooks...
                       [2016-08-04T00:13:08+00:00] WARN: Node chef-server-test has an empty run list.
                       Converging 0 resources
                       
                       Running handlers:
                       Running handlers complete
                       Chef Client finished, 0/0 resources updated in 03 seconds
    - run 'chef-client -c /etc/chef/client.rb -l auto' on chef-server-test
  * directory[/Users/sclark/development/tsa-dev/tsa-chef/cookbooks/delivery-cluster/.chef/../.chef/delivery-cluster-data-test] action create
    - create new directory /Users/sclark/development/tsa-dev/tsa-chef/cookbooks/delivery-cluster/.chef/../.chef/delivery-cluster-data-test
  * file[/Users/sclark/development/tsa-dev/tsa-chef/cookbooks/delivery-cluster/.chef/../.chef/delivery-cluster-data-test/chef_server_delivery_password] action create
    - create new file /Users/sclark/development/tsa-dev/tsa-chef/cookbooks/delivery-cluster/.chef/../.chef/delivery-cluster-data-test/chef_server_delivery_password
    - update content in file /Users/sclark/development/tsa-dev/tsa-chef/cookbooks/delivery-cluster/.chef/../.chef/delivery-cluster-data-test/chef_server_delivery_password from none to 82b31c
    - suppressed sensitive resource
    - change mode from '' to '0644'
  * machine[chef-server-test] action converge[2016-08-03T20:13:11-04:00] WARN: Class Chef::Provider::VagrantCluster does not declare 'provides :vagrant_cluster'.
[2016-08-03T20:13:11-04:00] WARN: This will no longer work in Chef 13: you must use 'provides' to use the resource's DSL.

    - update node chef-server-test at chefzero://localhost:8890
    -   add normal.chef-server-12 = {"accept_license"=>true, "delivery"=>{"organization"=>"test", "password"=>"C/CpZKriV9v3snvdjxj/ACASFS8="}, "api_fqdn"=>"10.0.2.15", "store_keys_databag"=>false, "plugin"=>{"reporting"=>true}, "data_collector"=>{"root_url"=>nil, "token"=>nil}}
    -   update run_list from [] to ["recipe[delivery-cluster::pkg_repo_management]", "recipe[chef-server-12]"]
    [chef-server-test] Starting Chef Client, version 12.12.15
