### ISSUE TITLE
converge error when rake setup:chef-server

### ISSUE THREAD

**Issue by ghao-ooyala** [chef-cookbooks/delivery-cluster#214]
I was trying to run rake setup:chef_server and getting converge error on chef-server; looks like a recent change in compat_resource (v12.10.5) caused the problem. It happens with delivery-cluster v0.6.11 and v0.6.12

```
resolving cookbooks for run list: ["delivery-cluster::setup_chef_server"]
Synchronizing Cookbooks:
  - delivery-cluster (0.6.11)
  - chef-ingredient (0.18.4)
  - chef-server-12 (0.1.13)
  - git (4.5.0)
  - apt (4.0.0)
  - yum (3.11.0)
  - delivery_build (0.4.26)
  - chef-splunk (1.5.0)
  - hostsfile (2.4.5)
  - build-essential (6.0.0)
  - dmg (2.4.0)
  - windows (1.43.0)
  - yum-epel (0.7.0)
  - compat_resource (12.10.5)
  - chef-sugar (3.3.0)
  - delivery-base (0.2.2)
  - chef-vault (1.3.3)
  - seven_zip (2.0.1)
  - mingw (1.1.0)
  - chef_handler (1.4.0)
  - push-jobs (3.1.0)
  - runit (1.7.7)
  - packagecloud (0.2.2)
Installing Cookbook Gems:
Compiling Cookbooks...
Converging 12 resources
Recipe: delivery-cluster::_settings
  * link[/root/chef-delivery/prod/delivery-cluster/.chef/../.chef/delivery-cluster-data] action create (up to date)
Recipe: delivery-cluster::setup_chef_server
  * machine[chef-server-ooyala] action converge
    
    ================================================================================
    Error executing action `converge` on resource 'machine[chef-server-ooyala]'
    ================================================================================
    
    NoMethodError
    -------------
    No resource or method named `delayed_actions' for `Cheffish::BasicChefClient "block"'
    
    Cookbook Trace:
    ---------------
    /root/chef-delivery/prod/delivery-cluster/.chef/local-mode-cache/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:34:in `delayed_actions'
    /root/chef-delivery/prod/delivery-cluster/.chef/local-mode-cache/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:41:in `run_action'
    
    Resource Declaration:
    ---------------------
    # In /root/chef-delivery/prod/delivery-cluster/.chef/local-mode-cache/cache/cookbooks/delivery-cluster/recipes/setup_chef_server.rb
    
     31: machine chef_server_hostname do
     32:   provisioning.specific_machine_options('chef-server').each do |option|
     33:     add_machine_options(option)
     34:   end
     35:   # Transfer any trusted certs
     36:   Dir.glob("#{Chef::Config[:trusted_certs_dir]}/*").each do |cert_path|
     37:     file ::File.join('/etc/chef/trusted_certs', ::File.basename(cert_path)), cert_path
     38:   end
     39:   action :converge
     40: end
     41: 
    
    Compiled Resource:
    ------------------
    # Declared in /root/chef-delivery/prod/delivery-cluster/.chef/local-mode-cache/cache/cookbooks/delivery-cluster/recipes/setup_chef_server.rb:31:in `from_file'
    
    machine("chef-server-ooyala") do
      action [:converge]
      retries 0
      retry_delay 2
      default_guard_interpreter :default
      chef_server {:chef_server_url=>"chefzero://localhost:8890", :options=>{:client_name=>"delivery", :signing_key_filename=>"/root/chef-delivery/prod/delivery-cluster/.chef/../.chef/delivery-cluster-data-ooyala/delivery.pem", :api_version=>"0"}}
      driver "ssh"
      machine_options #<Cheffish::MergedConfig:0x00000005c43cb8 @configs=[{:transport_options=>{:host=>"ip-10-50-41-102.sjc1.ooyala.net"}}, {:convergence_options=>{:bootstrap_proxy=>nil, :chef_config=>nil, :chef_version=>nil, :install_sh_path=>nil}, :transport_options=>{:username=>"root", :ssh_options=>{:user=>"root", :password=>nil, :keys=>["~/.ssh/id_rsa.pub"]}, :options=>{:prefix=>nil}}}], @merge_arrays={}>
      declared_type :machine
      cookbook_name "delivery-cluster"
      recipe_name "setup_chef_server"
      files {"/etc/chef/trusted_certs/delivery.sjc1.chef-delivery.services.ooyala.net.crt"=>"/root/chef-delivery/prod/delivery-cluster/.chef/trusted_certs/delivery.sjc1.chef-delivery.services.ooyala.net.crt", "/etc/chef/trusted_certs/ip-10-50-41-102.sjc1.ooyala.net.crt"=>"/root/chef-delivery/prod/delivery-cluster/.chef/trusted_certs/ip-10-50-41-102.sjc1.ooyala.net.crt", "/etc/chef/trusted_certs/delivery.sjc1.chef-delivery.services.ooyala.net.key"=>"/root/chef-delivery/prod/delivery-cluster/.chef/trusted_certs/delivery.sjc1.chef-delivery.services.ooyala.net.key", "/etc/chef/trusted_certs/ip-10-50-40-204.sjc1.ooyala.net.crt"=>"/root/chef-delivery/prod/delivery-cluster/.chef/trusted_certs/ip-10-50-40-204.sjc1.ooyala.net.crt", "/etc/chef/trusted_certs/ip-10-50-41-118.sjc1.ooyala.net.crt"=>"/root/chef-delivery/prod/delivery-cluster/.chef/trusted_certs/ip-10-50-41-118.sjc1.ooyala.net.crt"}
    end
    
    Platform:
    ---------
    x86_64-linux
    
```

**Comment by afiune** [comment]
@ghao-ooyala this was an external problem of delivery-cluster. We released a version of `compat_resource` that was causing problems with the new version of `chef-client`... We have fixed it so you should be good to go! Give it a try and if you find anything I can re-open this issue. Thanks
